# Symfony environment

version: '3'

services:
  php-fpm:
    container_name: php-fpm
    build:
      context: ./php7.1-fpm
      args:
        TIMEZONE: ${TIMEZONE}
    env_file: .env
    volumes:
      - ~/Documents/workspace:/var/www
    networks:
      - default

  nginx:
    container_name: nginx
    build: nginx
    ports:
      - 80:80
    volumes:
      - ./logs/nginx:/var/log/nginx
      - ~/Documents/workspace:/var/www
    networks:
      - default

  mariadb:
    container_name: mariadb
    image: mariadb
    env_file: .env
    ports:
      - 3306:3306
    volumes:
      - ./db:/var/lib/mysql
      - ./logs/mariadb:/var/log/mysql

  elk:
    container_name: elk
    image: willdurand/elk
    ports:
      - 81:80
    volumes:
      - ./elk/logstash:/etc/logstash
      - ./elk/logstash/patterns:/opt/logstash/patterns
      - ~/Documents/workspace:/var/www
      - ./logs/nginx:/var/log/nginx

networks:
  default:
    driver: bridge

