# Symfony environment

version: '3'

services:
  php-fpm:
    container_name: php-fpm
    build:
      context: ./php-fpm
      args:
        TIMEZONE: ${TIMEZONE}
    env_file: .env
    volumes:
      - ${WORKSPACE}:/var/www
    networks:
      - default

  nginx:
    container_name: nginx
    build: nginx
    ports:
      - 80:80
    volumes:
      - ${WORKSPACE}:/var/www
      - ./nginx/default:/etc/nginx/sites-enabled/default
      - ./logs/nginx:/var/log/nginx
    networks:
      - default

  mariadb:
    container_name: mariadb
    image: mariadb
    env_file: .env
    ports:
      - 3306:3306
    volumes:
      - ./db:/var/lib/mysql
      - ./logs/mariadb:/var/log/mysql

  elk:
    container_name: elk
    image: sebp/elk
    ports:
      - 5601:5601
      - 9200:9200
      - 5044:5044
    volumes:
      - ./elk/logstash/logstash.conf:/etc/logstash/conf.d/logstash.conf
      - ./elk/logstash/patterns:/opt/logstash/patterns
      - ${WORKSPACE}:/var/www
      - ./logs/nginx:/var/log/nginx

networks:
  default:
    driver: bridge

